---
title: "Synthetic India"
author: "Yiwen Sun"
date: "2024-06-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(readr)
sample4 <- read_csv("/Users/sunyiwen/Desktop/msc_thesis/methodology/data/3_final_processed_data/sample4_India.csv")

sample4 <- as.data.frame(sample4)

## Exclude those without complete pre-treatment EDI data
# define the pre-treatment period
pre_treatment_period <- 1970:1985

# identify countries with NAs during the pre-treatment period
countries_with_na <- sample4 %>%
  filter(year %in% pre_treatment_period) %>%
  group_by(countrycode) %>%
  summarize(has_na = any(is.na(exportdiv))) %>%
  filter(has_na) %>%
  pull(countrycode)

# exclude these countries from the dataset
sample4<- sample4 %>%
  filter(!countrycode %in% countries_with_na)


## Exclude those without any predictor variables available in the pre-treatment period
# specify the countries that need exclusion (from the dataprep function)
countries_to_exclude <- c(31, 729,887,24,784,180,262,226,566,634,740,762,860,894,192, 4, 116, 414, 68, 52, 834, 418,524, 558, 792, 324, 598)

# finalize the sample data to proceed
sample4 <- sample4 %>%
  filter(!countrycode %in% countries_to_exclude)

india.data <- dataprep(
  foo = sample4,
  predictors = c("ncc","pscom", "psenroll", "trade", "fdi", 
                                      "gdpg", "popn", "govscore", "latitude"),
  dependent = "exportdiv",
  unit.variable = "countrycode",
  unit.names.variable = "country",
  time.variable = "year",
  treatment.identifier = sample4$countrycode[sample4$country == "India"][1],
  controls.identifier = unique(sample4$countrycode[sample4$country != "India"]),
  time.predictors.prior = c(1970:1985),
  time.optimize.ssr = c(1970:1986),
  time.plot = c(1970:2014)
  )

india.synth <- synth(india.data)

path.plot(synth.res = india.synth,
          dataprep.res = india.data,
          tr.intake = 1986,
          Ylab = "Export Diversification Index",
          Xlab = " India ",
          Ylim = c(0, 5))
text(x=1970, y=4.5, labels = paste("MSPE=0.1053"), pos = 4)
```

the synthetic weights
```{r}
india.weights <- india.synth$solution.w
```


the treatment effects
```{r}
synthetic.outcome <- india.data$Y0plot %*% india.weights
actual.outcome <- sample4$exportdiv[sample4$country=="India" & sample4$year>1969]

india.treatment.effects <- actual.outcome - synthetic.outcome

actual.outcome
```


placebo test
```{r}
# start by plotting the treatment effects
plot(india.treatment.effects,
     type = "l",
     lwd = "2",
     ylim = c(-2.5, 2.5),
     xlab = " ",
     ylab = "Change in Export Diversification Index",
     xaxt = "n" )
axis(1, at=c(1, 10, 20, 30, 40), labels = c(1970, 1980, 1990, 2000, 2010))
abline(v=16, lty=3)
abline(h=0)
legend("topleft", c("India", "Placebo"), lty=c(1,2))


## adding the placebos
india.mspe <- mean((actual.outcome[1:16] - synthetic.outcome[1:16])^2)
# create a subset of untreated countries
sample4.controls <- subset(sample4, sample4$country != "Thailand")

# write a for loop to add the placebos one by one
for(i in 1:length(unique(sample4.controls$country))){
  my.country <- unique(sample4.controls$country)[i] # one country each time
  
  controls.data <- dataprep(sample4.controls,
                            predictors = c("ncc",
                                           "pscom", 
                                           "psenroll",
                                           "trade", 
                                           "fdi",
                                           "gdpg", 
                                           "popn", 
                                           "govscore", 
                                           "latitude"),
                            dependent = "exportdiv",
                           unit.variable = "countrycode",
                           unit.names.variable = "country",
                           time.variable = "year",
                           treatment.identifier = my.country,
                           controls.identifier = 
                             c(unique(sample4.controls$country[
                               sample4.controls$country != my.country])),
                           time.predictors.prior = c(1970:1987),
                           time.optimize.ssr = c(1970:1988),
                           time.plot = c(1970:2014)) # prep synth data for control group
  
  synth.control <- synth(controls.data)
  control.weights <- synth.control$solution.w
  
  placebo.synthetic.outcome <- controls.data$Y0plot %*% control.weights
  placebo.actual.outcome <- sample4$exportdiv[sample4$country == my.country & 
                                                sample4$year > 1969]
  placebo.treatment.effects <- placebo.actual.outcome - placebo.synthetic.outcome # estimate the treatment effects for the placebo units
  
  placebo.mspe <- mean((placebo.actual.outcome[1:16] - placebo.synthetic.outcome[1:16])^2)
  
  if(placebo.mspe <= 2 * india.mspe){
    lines(placebo.treatment.effects, lty = 2, lwd = 1, col = "grey") # plot the placebo units
  }
  
} ## end of the for loop
```














