---
title: "synthetic Chile"
author: "Yiwen Sun"
date: "2024-06-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
sample5 <- read_csv("/Users/sunyiwen/Desktop/msc_thesis/methodology/data/3_final_processed_data/sample5_chile.csv")
sample5 <- as.data.frame(sample5)

## Exclude those without complete pre-treatment EDI data
# define the pre-treatment period
pre_treatment_period <- 1970:1984

# identify countries with NAs during the pre-treatment period
countries_with_na <- sample5 %>%
  filter(year %in% pre_treatment_period) %>%
  group_by(countrycode) %>%
  summarize(has_na = any(is.na(exportdiv))) %>%
  filter(has_na) %>%
  pull(countrycode)

# exclude these countries from the dataset
sample5<- sample5 %>%
  filter(!countrycode %in% countries_with_na)


## Exclude those without any predictor variables available in the pre-treatment period
# specify the countries that need exclusion (from the dataprep function)
countries_to_exclude <- c(31, 729,887,24,784,180,262,226,566,634,740,762,860,894,192, 4, 116, 414, 68, 52, 834, 418,524, 558, 792, 324, 598, 710)

# finalize the sample data to proceed
sample5 <- sample5 %>%
  filter(!countrycode %in% countries_to_exclude)

sample5$popn <- log(sample5$popn)

chile.data <- dataprep(
  foo = sample5,
  predictors = c("ncc","pscom", "psenroll", "trade", "fdi", 
                                      "gdpg", "popn", "govscore", "latitude"),
  dependent = "exportdiv",
  unit.variable = "countrycode",
  unit.names.variable = "country",
  time.variable = "year",
  treatment.identifier = sample5$countrycode[sample5$country == "Chile"][1],
  controls.identifier = unique(sample5$countrycode[sample5$country != "Chile"]),
  time.predictors.prior = c(1970:1984),
  time.optimize.ssr = c(1970:1985),
  time.plot = c(1970:2014)
  )

chile.synth <- synth(chile.data)

path.plot(synth.res = chile.synth,
          dataprep.res = chile.data,
          tr.intake = 1985,
          Ylab = "Export Diversification Index",
          Xlab = "Chile",
          Ylim = c(1,6))
text(x=1970, y=5.5, labels = paste("MSPE=0.0684"), pos = 4)
```

the synthetic weights
```{r}
chile.weights <- chile.synth$solution.w
# 604, 480, 266, 608, 458
## Philippines, Mauritius, Gabon, Malaysia
```


the treatment effects
```{r}
synthetic.outcome <- chile.data$Y0plot %*% chile.weights
actual.outcome <- sample5$exportdiv[sample5$country=="Chile" & sample5$year>1969]
chile.treatment.effects <- actual.outcome - synthetic.outcome



plot(chile.treatment.effects,
     type = "l",
     lwd = "2",
     ylim = c(-2.5, 2.5),
     xlab = " Chile ",
     ylab = "Change in Export Diversification Index",
     xaxt = "n")
axis(1, at=c(1, 10, 20, 30, 40), labels = c(1970, 1980, 1990, 2000, 2010))
abline(v=15, lty=3)
abline(h=0)

actual.outcome
```


placebo test
```{r}
# start by plotting the treatment effects
plot(chile.treatment.effects,
     type = "l",
     lwd = "2",
     ylim = c(-2.5, 2.5),
     xlab = " ",
     ylab = "Change in Export Diversification Index",
     xaxt = "n" )
axis(1, at=c(1, 10, 20, 30, 40), labels = c(1970, 1980, 1990, 2000, 2010))
abline(v=15, lty=3)
abline(h=0)
legend("topleft", c("Chile", "Placebo"), lty=c(1,2))


## adding the placebos

chile.mspe <- mean((actual.outcome[1:15] - synthetic.outcome[1:15])^2)
# create a subset of untreated countries
sample5.controls <- subset(sample5, sample5$country != "Chile")

# write a for loop to add the placebos one by one
for(i in 1:length(unique(sample5.controls$country))){
  my.country <- unique(sample5.controls$country)[i] # one country each time
  
  tryCatch({
    controls.data <- dataprep(sample5.controls,
                              predictors = c("ncc",
                                             "pscom", 
                                             "psenroll",
                                             "trade", 
                                             "fdi",
                                             "gdpg", 
                                             "popn", 
                                             "govscore", 
                                             "latitude"),
                              dependent = "exportdiv",
                              unit.variable = "countrycode",
                              unit.names.variable = "country",
                              time.variable = "year",
                              treatment.identifier = my.country,
                              controls.identifier = 
                                c(unique(sample5.controls$country[
                                  sample5.controls$country != my.country])),
                              time.predictors.prior = c(1970:1984),
                              time.optimize.ssr = c(1970:1985),
                              time.plot = c(1970:2014)) # prep synth data for control group
    
    synth.control <- synth(controls.data)
    control.weights <- synth.control$solution.w
    
    placebo.synthetic.outcome <- controls.data$Y0plot %*% control.weights
    placebo.actual.outcome <- sample5$exportdiv[sample5$country == my.country & 
                                                  sample5$year > 1969]
    placebo.treatment.effects <- placebo.actual.outcome - placebo.synthetic.outcome # estimate the treatment effects for the placebo units
    
    placebo.mspe <- mean((placebo.actual.outcome[1:15] - placebo.synthetic.outcome[1:15])^2)
    
    if(placebo.mspe <= 5 * chile.mspe){
    lines(placebo.treatment.effects, lty = 2, lwd = 1, col = "grey")} # plot the placebo 
    
  }, error = function(e){
    cat("Error with country:", my.country, " - ", e$message, "\n")
  })
}
```

```















